### ISSUE TITLE
Support for TypeScript?

### ISSUE THREAD

**Issue by vladislav805** [RomiC/ya-disk#311]
Hello. Thank you for package.
Are there types for TypeScript? No `index.d.ts` in repository, no package `@types/ya-disk`.

**Comment by RomiC** [comment]
@vladislav805 hey!

No, there isn't any. But the lib is well documented with JSDoc, including API responses.

**Comment by vladislav805** [comment]
Yeah, i see jsdoc in code, but for a project that uses typescript, all function signatures, parameters, and etc description in ts file are required. If typings not present for external package, it will throw error on strict mode and all variables set to ` any`:
![image](https://user-images.githubusercontent.com/10882576/107881450-742bc300-6ef5-11eb-9d3f-d0cf03438e36.png)

If I prepare a types description based on jsdoc, can I create a pull request or would you prefer the types to be in [@DefinitelyTyped/DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)?

**Comment by RomiC** [comment]
@vladislav805 if it's OK for you, I'll prefer to see types in [@DefinitelyTyped/DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) instead of this repo, as I don't have plans to support typing so far. Most likely the project will migrate to TS in the future.

**Comment by vladislav805** [comment]
Added in DefinitelyTyped/DefinitelyTyped#52796 as package `@types/ya-disk`.
